version: '3.7'
services:
    app:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: pet
        container_name: pet-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - './:/var/www'
        networks:
            - pet
    db:
        image: 'mysql:8.0'
        container_name: pet-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - './docker-compose/mysql:/docker-entrypoint-initdb.d'
        networks:
            - pet
    nginx:
        image: 'nginx:alpine'
        container_name: pet-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
            - '443:443'
        volumes:
            - './:/var/www'
            - './docker-compose/nginx:/etc/nginx/conf.d/'
        networks:
            - pet
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pet-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '8080:80'
        networks:
            - pet
networks:
    pet:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
